version: "3"
services:
  db:
    image: postgres:15
    platform: linux/arm64/v8
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
      POSTGRES_USER: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  back:
    platform: linux/arm64/v8
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.local
      - ./backend/.env.development 
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/app
      - bundle_data:/usr/local/bundle # Gemの永続化のために追加
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true
  front:
    platform: linux/arm64/v8
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      -  front_node_modules:/app/node_modules  # 明示的に永続化
    stdin_open: true
    tty: true
volumes:
  postgresql_data:
  bundle_data:
  front_node_modules: